### PR TITLE
Fix move bug on std::ofstream in driver code

### LINKED ISSUE #110: Latest updates do not compile on GCC 4.8.5
I have GCC 4.8.5. I get this error at build:

ngen/src/NGen.cpp:229:33: error: use of deleted function ‘std::basic_ofstream<char>& std::basic_ofstream<char>::operator=(const std::basic_ofstream<char>&)’
         nexus_outfiles[feat_id] = std::ofstream("./"+feature->get_id()+"_output.csv", std::ios::trunc);

## Expected behavior
My build worked fine with Donald's recent PR before pulling the latest updates from June 30 and July 1.

### PR DESCRIPTION
**Pull request by hellkite500**
Closes #110 

## Changes

- directly `open()` the outfile stream instead of constructing the stream and assigning the open stream to the map

## Testing

1. Re-ran the driver locally and was able to produce the appropriate nexus outflows

## Checklist

- [x] PR has an informative and human-readable title
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows project standards (link if applicable)
- [x] Passes all existing automated tests
- [x] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future todos are captured in comments
- [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [x] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### Target Environment support

- [x] Linux

### CODE REVIEW

**Comment by hellkite500** [comment]
Included in #113
